// <auto-generated />
using System;
using ItFormationCentre.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItFormationCentre.Migrations
{
    [DbContext(typeof(ItFormationCentreDbContext))]
    [Migration("20250501130019_Update1")]
    partial class Update1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ItFormationCentre.Models.Adresse", b =>
                {
                    b.Property<int>("IdAdresse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdresse"));

                    b.Property<int>("IdLocalite")
                        .HasColumnType("int");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAdresse");

                    b.HasIndex("IdLocalite");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Ajouter", b =>
                {
                    b.Property<int>("IdPanier")
                        .HasColumnType("int");

                    b.Property<int>("IdFormation")
                        .HasColumnType("int");

                    b.Property<int>("IdAjouter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAjouter"));

                    b.HasKey("IdPanier", "IdFormation");

                    b.HasIndex("IdFormation");

                    b.ToTable("Ajouts");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Detenir", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdPermission")
                        .HasColumnType("int");

                    b.HasKey("IdRole", "IdPermission");

                    b.HasIndex("IdPermission");

                    b.ToTable("Detentions");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Evaluation", b =>
                {
                    b.Property<int>("IdEvaluation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvaluation"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEvaluation")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FormateurIdUtilisateur")
                        .HasColumnType("int");

                    b.Property<int?>("FormateurIdUtilisateur1")
                        .HasColumnType("int");

                    b.Property<int>("IdSessionFormation")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilisateurFormateur")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilisateurStagiaire")
                        .HasColumnType("int");

                    b.Property<decimal>("Note")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SessionFormationIdSessionFormation")
                        .HasColumnType("int");

                    b.Property<int?>("StagiaireIdUtilisateur")
                        .HasColumnType("int");

                    b.Property<int?>("UtilisateurIdUtilisateur")
                        .HasColumnType("int");

                    b.HasKey("IdEvaluation");

                    b.HasIndex("FormateurIdUtilisateur");

                    b.HasIndex("FormateurIdUtilisateur1");

                    b.HasIndex("IdSessionFormation");

                    b.HasIndex("IdUtilisateurFormateur");

                    b.HasIndex("IdUtilisateurStagiaire");

                    b.HasIndex("SessionFormationIdSessionFormation");

                    b.HasIndex("StagiaireIdUtilisateur");

                    b.HasIndex("UtilisateurIdUtilisateur");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Formation", b =>
                {
                    b.Property<int>("IdFormation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFormation"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duree")
                        .HasColumnType("int");

                    b.Property<string>("NomFormation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdFormation");

                    b.ToTable("Formations");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Heure", b =>
                {
                    b.Property<int>("IdHeure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHeure"));

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("time");

                    b.HasKey("IdHeure");

                    b.ToTable("Heures");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Inscription", b =>
                {
                    b.Property<int>("IdInscription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInscription"));

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSessionFormation")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdInscription");

                    b.HasIndex("IdSessionFormation");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("Inscriptions");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Local", b =>
                {
                    b.Property<int>("IdLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocal"));

                    b.Property<int>("Capacite")
                        .HasColumnType("int");

                    b.Property<string>("Disponibilite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroLocal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SessionFormationIdSessionFormation")
                        .HasColumnType("int");

                    b.HasKey("IdLocal");

                    b.HasIndex("SessionFormationIdSessionFormation");

                    b.ToTable("Local");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Localite", b =>
                {
                    b.Property<int>("IdLocalite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocalite"));

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NomLocalite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdLocalite");

                    b.ToTable("Localites");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Paiement", b =>
                {
                    b.Property<int>("IdPaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaiement"));

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdInscription")
                        .HasColumnType("int");

                    b.Property<int>("IdPanier")
                        .HasColumnType("int");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StatutPaiement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypePaiement")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPaiement");

                    b.HasIndex("IdInscription");

                    b.HasIndex("IdPanier");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Panier", b =>
                {
                    b.Property<int>("IdPanier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPanier"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPanier");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("Paniers");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Permission", b =>
                {
                    b.Property<int>("IdPermission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermission"));

                    b.Property<string>("IntitulePermission")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPermission");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Plannifier", b =>
                {
                    b.Property<int>("IdSessionFormation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdHeure")
                        .HasColumnType("int");

                    b.HasKey("IdSessionFormation", "IdHeure");

                    b.HasIndex("IdHeure");

                    b.ToTable("Plannifications");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<string>("IntituleRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdRole");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ItFormationCentre.Models.SessionFormation", b =>
                {
                    b.Property<int>("IdSessionFormation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSessionFormation"));

                    b.Property<int?>("FormateurIdUtilisateur")
                        .HasColumnType("int");

                    b.Property<int>("IdFormation")
                        .HasColumnType("int");

                    b.Property<int>("IdLocalite")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.HasKey("IdSessionFormation");

                    b.HasIndex("FormateurIdUtilisateur");

                    b.HasIndex("IdFormation");

                    b.HasIndex("IdLocalite");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("SessionsFormation");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<string>("Diplome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAdresse")
                        .HasColumnType("int");

                    b.Property<int>("IdLocalite")
                        .HasColumnType("int");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("IdUtilisateur");

                    b.HasIndex("IdAdresse");

                    b.HasIndex("IdLocalite");

                    b.HasIndex("IdRole");

                    b.ToTable("Utilisateurs", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("Utilisateur");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ItFormationCentre.Models.Formateur", b =>
                {
                    b.HasBaseType("ItFormationCentre.Models.Utilisateur");

                    b.Property<string>("Specialite")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Formateur");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Stagiaire", b =>
                {
                    b.HasBaseType("ItFormationCentre.Models.Utilisateur");

                    b.Property<string>("CarteEtudiant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Stagiaire");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Adresse", b =>
                {
                    b.HasOne("ItFormationCentre.Models.Localite", "Localite")
                        .WithMany()
                        .HasForeignKey("IdLocalite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localite");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Ajouter", b =>
                {
                    b.HasOne("ItFormationCentre.Models.Formation", "Formation")
                        .WithMany("Paniers")
                        .HasForeignKey("IdFormation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItFormationCentre.Models.Panier", "Panier")
                        .WithMany("Ajouts")
                        .HasForeignKey("IdPanier")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Formation");

                    b.Navigation("Panier");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Detenir", b =>
                {
                    b.HasOne("ItFormationCentre.Models.Permission", "Permission")
                        .WithMany("Roles")
                        .HasForeignKey("IdPermission")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItFormationCentre.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Evaluation", b =>
                {
                    b.HasOne("ItFormationCentre.Models.Formateur", null)
                        .WithMany("Evaluations")
                        .HasForeignKey("FormateurIdUtilisateur");

                    b.HasOne("ItFormationCentre.Models.Formateur", null)
                        .WithMany("EvaluationsStagiaire")
                        .HasForeignKey("FormateurIdUtilisateur1");

                    b.HasOne("ItFormationCentre.Models.SessionFormation", "SessionFormation")
                        .WithMany()
                        .HasForeignKey("IdSessionFormation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItFormationCentre.Models.Formateur", "Formateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateurFormateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItFormationCentre.Models.Stagiaire", "Stagiaire")
                        .WithMany("EvaluationsStagiaire")
                        .HasForeignKey("IdUtilisateurStagiaire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItFormationCentre.Models.SessionFormation", null)
                        .WithMany("Evaluations")
                        .HasForeignKey("SessionFormationIdSessionFormation");

                    b.HasOne("ItFormationCentre.Models.Stagiaire", null)
                        .WithMany("Evaluations")
                        .HasForeignKey("StagiaireIdUtilisateur");

                    b.HasOne("ItFormationCentre.Models.Utilisateur", null)
                        .WithMany("EvaluationsFormateur")
                        .HasForeignKey("UtilisateurIdUtilisateur");

                    b.Navigation("Formateur");

                    b.Navigation("SessionFormation");

                    b.Navigation("Stagiaire");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Inscription", b =>
                {
                    b.HasOne("ItFormationCentre.Models.SessionFormation", "SessionFormation")
                        .WithMany("Inscriptions")
                        .HasForeignKey("IdSessionFormation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItFormationCentre.Models.Stagiaire", "Stagiaire")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SessionFormation");

                    b.Navigation("Stagiaire");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Local", b =>
                {
                    b.HasOne("ItFormationCentre.Models.SessionFormation", null)
                        .WithMany("Locaux")
                        .HasForeignKey("SessionFormationIdSessionFormation");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Paiement", b =>
                {
                    b.HasOne("ItFormationCentre.Models.Inscription", "Inscription")
                        .WithMany()
                        .HasForeignKey("IdInscription")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItFormationCentre.Models.Panier", "Panier")
                        .WithMany()
                        .HasForeignKey("IdPanier")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inscription");

                    b.Navigation("Panier");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Panier", b =>
                {
                    b.HasOne("ItFormationCentre.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Plannifier", b =>
                {
                    b.HasOne("ItFormationCentre.Models.Heure", "Heure")
                        .WithMany("SessionsFormation")
                        .HasForeignKey("IdHeure")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItFormationCentre.Models.SessionFormation", "SessionFormation")
                        .WithMany("Heures")
                        .HasForeignKey("IdSessionFormation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Heure");

                    b.Navigation("SessionFormation");
                });

            modelBuilder.Entity("ItFormationCentre.Models.SessionFormation", b =>
                {
                    b.HasOne("ItFormationCentre.Models.Formateur", null)
                        .WithMany("Sessions")
                        .HasForeignKey("FormateurIdUtilisateur");

                    b.HasOne("ItFormationCentre.Models.Formation", "Formation")
                        .WithMany("SessionsFormation")
                        .HasForeignKey("IdFormation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItFormationCentre.Models.Localite", "Localite")
                        .WithMany("SessionsFormation")
                        .HasForeignKey("IdLocalite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItFormationCentre.Models.Formateur", "Formateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Formateur");

                    b.Navigation("Formation");

                    b.Navigation("Localite");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Utilisateur", b =>
                {
                    b.HasOne("ItFormationCentre.Models.Adresse", "Adresse")
                        .WithMany()
                        .HasForeignKey("IdAdresse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItFormationCentre.Models.Localite", "Localite")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdLocalite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItFormationCentre.Models.Role", "Role")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Adresse");

                    b.Navigation("Localite");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Formation", b =>
                {
                    b.Navigation("Paniers");

                    b.Navigation("SessionsFormation");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Heure", b =>
                {
                    b.Navigation("SessionsFormation");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Localite", b =>
                {
                    b.Navigation("SessionsFormation");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Panier", b =>
                {
                    b.Navigation("Ajouts");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Permission", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("ItFormationCentre.Models.SessionFormation", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("Heures");

                    b.Navigation("Inscriptions");

                    b.Navigation("Locaux");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Utilisateur", b =>
                {
                    b.Navigation("EvaluationsFormateur");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Formateur", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("EvaluationsStagiaire");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Stagiaire", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("EvaluationsStagiaire");
                });
#pragma warning restore 612, 618
        }
    }
}
