// <auto-generated />
using System;
using ItFormationCentre.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItFormationCentre.Migrations
{
    [DbContext(typeof(ItFormationCentreDbContext))]
    partial class ItFormationCentreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ItFormationCentre.Models.Ajouter", b =>
                {
                    b.Property<int>("IdPanier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdFormation")
                        .HasColumnType("int");

                    b.HasKey("IdPanier");

                    b.HasIndex("IdFormation");

                    b.ToTable("Ajouts");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Detenir", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdPermission")
                        .HasColumnType("int");

                    b.HasKey("IdRole");

                    b.HasIndex("IdPermission");

                    b.ToTable("Detentions");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Evaluation", b =>
                {
                    b.Property<int>("IdEvaluation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvaluation"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEvaluation")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSessionFormation")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<float>("Note")
                        .HasColumnType("real");

                    b.Property<int?>("SessionFormationIdSessionFormation")
                        .HasColumnType("int");

                    b.Property<int?>("UtilisateurIdUtilisateur")
                        .HasColumnType("int");

                    b.HasKey("IdEvaluation");

                    b.HasIndex("SessionFormationIdSessionFormation");

                    b.HasIndex("UtilisateurIdUtilisateur");

                    b.ToTable("Evaluation");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Formation", b =>
                {
                    b.Property<int>("IdFormation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFormation"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duree")
                        .HasColumnType("int");

                    b.Property<string>("NomFormation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdFormation");

                    b.ToTable("Formations");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Heure", b =>
                {
                    b.Property<int>("IdHeure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHeure"));

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("time");

                    b.HasKey("IdHeure");

                    b.ToTable("Heures");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Inscription", b =>
                {
                    b.Property<int>("IdInscription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInscription"));

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSessionFormation")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<int?>("SessionFormationIdSessionFormation")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UtilisateurIdUtilisateur")
                        .HasColumnType("int");

                    b.HasKey("IdInscription");

                    b.HasIndex("SessionFormationIdSessionFormation");

                    b.HasIndex("UtilisateurIdUtilisateur");

                    b.ToTable("Inscription");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Localite", b =>
                {
                    b.Property<int>("IdLocalite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocalite"));

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NomLocalite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SessionFormationIdSessionFormation")
                        .HasColumnType("int");

                    b.HasKey("IdLocalite");

                    b.HasIndex("SessionFormationIdSessionFormation");

                    b.ToTable("Localites");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Panier", b =>
                {
                    b.Property<int>("IdPanier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPanier"));

                    b.Property<string>("CodePromo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("MethodePaiement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NetAPayer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Reduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Statut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UtilisateurIdUtilisateur")
                        .HasColumnType("int");

                    b.HasKey("IdPanier");

                    b.HasIndex("UtilisateurIdUtilisateur");

                    b.ToTable("Paniers");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Permission", b =>
                {
                    b.Property<int>("IdPermission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermission"));

                    b.Property<string>("IntitulePermission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPermission");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Planifier", b =>
                {
                    b.Property<int>("IdSessionFormation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdHeure")
                        .HasColumnType("int");

                    b.HasKey("IdSessionFormation");

                    b.HasIndex("IdHeure");

                    b.ToTable("Planifications");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<string>("IntituleRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdRole");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ItFormationCentre.Models.SessionFormation", b =>
                {
                    b.Property<int>("IdSessionFormation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSessionFormation"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FormationIdFormation")
                        .HasColumnType("int");

                    b.Property<int>("IdFormation")
                        .HasColumnType("int");

                    b.Property<int>("NombreParticipant")
                        .HasColumnType("int");

                    b.Property<string>("StatusSession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSessionFormation");

                    b.HasIndex("FormationIdFormation");

                    b.ToTable("SessionFormations");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdLocalite")
                        .HasColumnType("int");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<int?>("LocaliteIdLocalite")
                        .HasColumnType("int");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RoleIdRole")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUtilisateur");

                    b.HasIndex("LocaliteIdLocalite");

                    b.HasIndex("RoleIdRole");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<int>("PermissionsIdPermission")
                        .HasColumnType("int");

                    b.Property<int>("RolesIdRole")
                        .HasColumnType("int");

                    b.HasKey("PermissionsIdPermission", "RolesIdRole");

                    b.HasIndex("RolesIdRole");

                    b.ToTable("PermissionRole");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Ajouter", b =>
                {
                    b.HasOne("ItFormationCentre.Models.Formation", "Formation")
                        .WithMany()
                        .HasForeignKey("IdFormation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItFormationCentre.Models.Panier", "Panier")
                        .WithMany()
                        .HasForeignKey("IdPanier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formation");

                    b.Navigation("Panier");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Detenir", b =>
                {
                    b.HasOne("ItFormationCentre.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("IdPermission")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItFormationCentre.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Evaluation", b =>
                {
                    b.HasOne("ItFormationCentre.Models.SessionFormation", "SessionFormation")
                        .WithMany("Evaluations")
                        .HasForeignKey("SessionFormationIdSessionFormation");

                    b.HasOne("ItFormationCentre.Models.Utilisateur", "Utilisateur")
                        .WithMany("Evaluations")
                        .HasForeignKey("UtilisateurIdUtilisateur");

                    b.Navigation("SessionFormation");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Inscription", b =>
                {
                    b.HasOne("ItFormationCentre.Models.SessionFormation", "SessionFormation")
                        .WithMany("Inscriptions")
                        .HasForeignKey("SessionFormationIdSessionFormation");

                    b.HasOne("ItFormationCentre.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurIdUtilisateur");

                    b.Navigation("SessionFormation");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Localite", b =>
                {
                    b.HasOne("ItFormationCentre.Models.SessionFormation", null)
                        .WithMany("Localites")
                        .HasForeignKey("SessionFormationIdSessionFormation");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Panier", b =>
                {
                    b.HasOne("ItFormationCentre.Models.Utilisateur", "Utilisateur")
                        .WithMany("Paniers")
                        .HasForeignKey("UtilisateurIdUtilisateur");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Planifier", b =>
                {
                    b.HasOne("ItFormationCentre.Models.Heure", "Heure")
                        .WithMany()
                        .HasForeignKey("IdHeure")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItFormationCentre.Models.SessionFormation", "SessionFormation")
                        .WithMany()
                        .HasForeignKey("IdSessionFormation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heure");

                    b.Navigation("SessionFormation");
                });

            modelBuilder.Entity("ItFormationCentre.Models.SessionFormation", b =>
                {
                    b.HasOne("ItFormationCentre.Models.Formation", "Formation")
                        .WithMany("Sessions")
                        .HasForeignKey("FormationIdFormation");

                    b.Navigation("Formation");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Utilisateur", b =>
                {
                    b.HasOne("ItFormationCentre.Models.Localite", "Localite")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("LocaliteIdLocalite");

                    b.HasOne("ItFormationCentre.Models.Role", "Role")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("RoleIdRole");

                    b.Navigation("Localite");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("ItFormationCentre.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsIdPermission")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItFormationCentre.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesIdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItFormationCentre.Models.Formation", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Localite", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Role", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("ItFormationCentre.Models.SessionFormation", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("Inscriptions");

                    b.Navigation("Localites");
                });

            modelBuilder.Entity("ItFormationCentre.Models.Utilisateur", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("Paniers");
                });
#pragma warning restore 612, 618
        }
    }
}
