// <auto-generated />
using System;
using EcommerceApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceApplication.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    partial class ECommerceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcommerceApplication.Models.Ajouter", b =>
                {
                    b.Property<int>("IdPanier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdProduit")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("IdPanier", "IdProduit");

                    b.HasIndex("IdProduit");

                    b.ToTable("Ajouter");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Appartenir", b =>
                {
                    b.Property<int>("IdCategorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdProduit")
                        .HasColumnType("int");

                    b.HasKey("IdCategorie", "IdProduit");

                    b.HasIndex("IdProduit");

                    b.ToTable("Appartenir");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Categorie", b =>
                {
                    b.Property<int>("IdCategorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategorie"));

                    b.Property<string>("NomCategorie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCategorie");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Commande", b =>
                {
                    b.Property<int>("IdCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCommande"));

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPanier")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UtilisateurIdUtilisateur")
                        .HasColumnType("int");

                    b.HasKey("IdCommande");

                    b.HasIndex("IdPanier");

                    b.HasIndex("IdUtilisateur");

                    b.HasIndex("UtilisateurIdUtilisateur");

                    b.ToTable("Commande");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Contenir", b =>
                {
                    b.Property<int>("IdCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdProduit")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("IdCommande", "IdProduit");

                    b.HasIndex("IdProduit");

                    b.ToTable("Contenir");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Detenir", b =>
                {
                    b.Property<int>("IdPermission")
                        .HasColumnType("int");

                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("IdPermission", "IdRole");

                    b.HasIndex("IdRole");

                    b.ToTable("Detenir");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Localite", b =>
                {
                    b.Property<int>("IdLocalite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocalite"));

                    b.Property<int>("CodePostal")
                        .HasColumnType("int");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomLocalite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLocalite");

                    b.ToTable("Localite");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Panier", b =>
                {
                    b.Property<int>("IdPanier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPanier"));

                    b.Property<DateTime>("DatePanier")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<int?>("UtilisateurIdUtilisateur")
                        .HasColumnType("int");

                    b.HasKey("IdPanier");

                    b.HasIndex("IdUtilisateur");

                    b.HasIndex("UtilisateurIdUtilisateur");

                    b.ToTable("Panier");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Permission", b =>
                {
                    b.Property<int>("IdPermission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermission"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPermission");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Produit", b =>
                {
                    b.Property<int>("IdProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduit"));

                    b.Property<int>("CategorieIdCategorie")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionProduit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdCategorie")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("IdTVA")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("IdProduit");

                    b.HasIndex("CategorieIdCategorie");

                    b.HasIndex("IdTVA");

                    b.ToTable("Produit");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<string>("DetailRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntituleRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRole");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("EcommerceApplication.Models.TVA", b =>
                {
                    b.Property<int>("IdTVA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTVA"));

                    b.Property<int>("TauxTva")
                        .HasColumnType("int");

                    b.Property<string>("TypeProduitTva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTVA");

                    b.ToTable("TVA");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdLocalite")
                        .HasColumnType("int");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUtilisateur");

                    b.HasIndex("IdLocalite");

                    b.HasIndex("IdRole");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Ajouter", b =>
                {
                    b.HasOne("EcommerceApplication.Models.Panier", "Panier")
                        .WithMany()
                        .HasForeignKey("IdPanier")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcommerceApplication.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("IdProduit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Panier");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Appartenir", b =>
                {
                    b.HasOne("EcommerceApplication.Models.Categorie", "Categorie")
                        .WithMany()
                        .HasForeignKey("IdCategorie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcommerceApplication.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("IdProduit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Commande", b =>
                {
                    b.HasOne("EcommerceApplication.Models.Panier", null)
                        .WithMany()
                        .HasForeignKey("IdPanier")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcommerceApplication.Models.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcommerceApplication.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurIdUtilisateur");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Contenir", b =>
                {
                    b.HasOne("EcommerceApplication.Models.Commande", "Commande")
                        .WithMany()
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcommerceApplication.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("IdProduit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Detenir", b =>
                {
                    b.HasOne("EcommerceApplication.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("IdPermission")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcommerceApplication.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Panier", b =>
                {
                    b.HasOne("EcommerceApplication.Models.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EcommerceApplication.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurIdUtilisateur");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Produit", b =>
                {
                    b.HasOne("EcommerceApplication.Models.Categorie", "Categorie")
                        .WithMany()
                        .HasForeignKey("CategorieIdCategorie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceApplication.Models.TVA", null)
                        .WithMany()
                        .HasForeignKey("IdTVA")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Utilisateur", b =>
                {
                    b.HasOne("EcommerceApplication.Models.Localite", "Localite")
                        .WithMany("Utilisateur")
                        .HasForeignKey("IdLocalite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcommerceApplication.Models.Role", "Role")
                        .WithMany("Utilisateur")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Localite");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Localite", b =>
                {
                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("EcommerceApplication.Models.Role", b =>
                {
                    b.Navigation("Utilisateur");
                });
#pragma warning restore 612, 618
        }
    }
}
